/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: jetty/12.0.21
 * Generated at: 2026-06-30 06:26:47 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import jakarta.servlet.*;
import jakarta.servlet.http.*;
import jakarta.servlet.jsp.*;

public final class accommodation_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports,
                 org.apache.jasper.runtime.JspSourceDirectives {

  private static final jakarta.servlet.jsp.JspFactory _jspxFactory =
          jakarta.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(1);
    _jspx_dependants.put("/WEB-INF/includes/nav.jsp", Long.valueOf(1782799811895L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.LinkedHashSet<>(4);
    _jspx_imports_packages.add("jakarta.servlet");
    _jspx_imports_packages.add("jakarta.servlet.http");
    _jspx_imports_packages.add("jakarta.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile jakarta.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public boolean getErrorOnELNotFound() {
    return false;
  }

  public jakarta.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final jakarta.servlet.http.HttpServletRequest request, final jakarta.servlet.http.HttpServletResponse response)
      throws java.io.IOException, jakarta.servlet.ServletException {

    if (!jakarta.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final jakarta.servlet.jsp.PageContext pageContext;
    jakarta.servlet.http.HttpSession session = null;
    final jakarta.servlet.ServletContext application;
    final jakarta.servlet.ServletConfig config;
    jakarta.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    jakarta.servlet.jsp.JspWriter _jspx_out = null;
    jakarta.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\n");
      out.write("<!DOCTYPE html>\n");
      out.write("<html lang=\"en\">\n");
      out.write("<head>\n");
      out.write("    <meta charset=\"UTF-8\">\n");
      out.write("    <meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">\n");
      out.write("    <title>Accommodation — Kuala Selangor Tourism</title>\n");
      out.write("    <link rel=\"stylesheet\" href=\"https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css\">\n");
      out.write("    <link rel=\"stylesheet\" href=\"https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.5.0/css/all.min.css\">\n");
      out.write("    <link rel=\"stylesheet\" href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/css/style.css\">\n");
      out.write("</head>\n");
      out.write("<body>\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("<nav class=\"navbar navbar-expand-lg\">\n");
      out.write("    <div class=\"container\">\n");
      out.write("        <a class=\"navbar-brand\" href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/index.jsp\">\n");
      out.write("            <img src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/images/vm2026/logo.png\"\n");
      out.write("                 alt=\"Visit Malaysia 2026\"\n");
      out.write("                 class=\"vm-logo\">\n");
      out.write("            <span class=\"brand-sep\"></span>\n");
      out.write("            <span class=\"brand-name\">Kuala <span>Selangor</span></span>\n");
      out.write("        </a>\n");
      out.write("        <button class=\"navbar-toggler\" type=\"button\" data-bs-toggle=\"collapse\"\n");
      out.write("                data-bs-target=\"#mainNav\" aria-controls=\"mainNav\"\n");
      out.write("                aria-expanded=\"false\" aria-label=\"Toggle navigation\">\n");
      out.write("            <span class=\"navbar-toggler-icon\"></span>\n");
      out.write("        </button>\n");
      out.write("        <div class=\"collapse navbar-collapse\" id=\"mainNav\">\n");
      out.write("            <ul class=\"navbar-nav ms-auto\">\n");
      out.write("                <li class=\"nav-item\">\n");
      out.write("                    <a class=\"nav-link\" href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/index.jsp\">Home</a>\n");
      out.write("                </li>\n");
      out.write("                <li class=\"nav-item\">\n");
      out.write("                    <a class=\"nav-link\" href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/gallery.jsp\">Gallery</a>\n");
      out.write("                </li>\n");
      out.write("                <li class=\"nav-item\">\n");
      out.write("                    <a class=\"nav-link\" href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/activities.jsp\">Activities</a>\n");
      out.write("                </li>\n");
      out.write("                <li class=\"nav-item\">\n");
      out.write("                    <a class=\"nav-link\" href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/accommodation.jsp\">Accommodation</a>\n");
      out.write("                </li>\n");
      out.write("                <li class=\"nav-item\">\n");
      out.write("                    <a class=\"nav-link\" href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/contact.jsp\">Contact</a>\n");
      out.write("                </li>\n");
      out.write("                <li class=\"nav-item\">\n");
      out.write("                    <a class=\"nav-link\" href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/developer.jsp\">Developer</a>\n");
      out.write("                </li>\n");
      out.write("            </ul>\n");
      out.write("        </div>\n");
      out.write("    </div>\n");
      out.write("</nav>\n");
      out.write("<div class=\"vm-stripe\"></div>\n");
      out.write("\n");
      out.write("\n");
      out.write("<div class=\"page-header\">\n");
      out.write("    <h1>Where To Stay</h1>\n");
      out.write("    <p>4 comfortable options for every type of traveller</p>\n");
      out.write("</div>\n");
      out.write("\n");
      out.write("<section class=\"section-padding\">\n");
      out.write("    <div class=\"container\">\n");
      out.write("        <div class=\"text-center mb-5\">\n");
      out.write("            <h2 class=\"section-title\">Accommodation in Kuala Selangor</h2>\n");
      out.write("            <hr class=\"title-divider mx-auto\">\n");
      out.write("            <p class=\"section-subtitle\">From riverside resorts to budget homestays — rest well after a day of adventure</p>\n");
      out.write("        </div>\n");
      out.write("\n");
      out.write("        <div class=\"row g-4\">\n");
      out.write("\n");
      out.write("            <!-- Accommodation 1 -->\n");
      out.write("            <div class=\"col-md-6\">\n");
      out.write("                <div class=\"feature-card\">\n");
      out.write("                    <img src=\"https://picsum.photos/seed/firefly-park-resort/700/400\"\n");
      out.write("                         alt=\"Firefly Park Resort\">\n");
      out.write("                    <div class=\"card-body\">\n");
      out.write("                        <div class=\"card-badge\"><i class=\"fas fa-star me-1\"></i>4-Star Resort</div>\n");
      out.write("                        <h4 class=\"card-title\">Firefly Park Resort</h4>\n");
      out.write("                        <p class=\"card-text\">\n");
      out.write("                            Nestled along the banks of the Selangor River, Firefly Park Resort is the\n");
      out.write("                            premier accommodation choice in Kuala Selangor. Chalets and garden rooms\n");
      out.write("                            are set amidst lush greenery with direct access to the firefly boat cruise.\n");
      out.write("                            Amenities include a swimming pool, restaurant, and guided nature tours.\n");
      out.write("                            Perfect for families and couples seeking a nature retreat.\n");
      out.write("                        </p>\n");
      out.write("                        <div class=\"mt-3 d-flex gap-3 flex-wrap\">\n");
      out.write("                            <span class=\"text-muted small\"><i class=\"fas fa-tag me-1\"></i>From RM 180/night</span>\n");
      out.write("                            <span class=\"text-muted small\"><i class=\"fas fa-wifi me-1\"></i>Free WiFi</span>\n");
      out.write("                            <span class=\"text-muted small\"><i class=\"fas fa-swimming-pool me-1\"></i>Pool</span>\n");
      out.write("                        </div>\n");
      out.write("                    </div>\n");
      out.write("                </div>\n");
      out.write("            </div>\n");
      out.write("\n");
      out.write("            <!-- Accommodation 2 -->\n");
      out.write("            <div class=\"col-md-6\">\n");
      out.write("                <div class=\"feature-card\">\n");
      out.write("                    <img src=\"https://picsum.photos/seed/de-palma-hotel/700/400\"\n");
      out.write("                         alt=\"De Palma Hotel Kuala Selangor\">\n");
      out.write("                    <div class=\"card-body\">\n");
      out.write("                        <div class=\"card-badge\"><i class=\"fas fa-hotel me-1\"></i>3-Star Hotel</div>\n");
      out.write("                        <h4 class=\"card-title\">De Palma Hotel</h4>\n");
      out.write("                        <p class=\"card-text\">\n");
      out.write("                            A comfortable and well-appointed hotel located in the heart of Kuala\n");
      out.write("                            Selangor town. De Palma Hotel offers spacious rooms, a halal restaurant\n");
      out.write("                            serving local and international cuisine, a function hall, and meeting\n");
      out.write("                            facilities. Conveniently located near Bukit Melawati and the town centre,\n");
      out.write("                            it is ideal for both leisure and business travellers.\n");
      out.write("                        </p>\n");
      out.write("                        <div class=\"mt-3 d-flex gap-3 flex-wrap\">\n");
      out.write("                            <span class=\"text-muted small\"><i class=\"fas fa-tag me-1\"></i>From RM 120/night</span>\n");
      out.write("                            <span class=\"text-muted small\"><i class=\"fas fa-wifi me-1\"></i>Free WiFi</span>\n");
      out.write("                            <span class=\"text-muted small\"><i class=\"fas fa-utensils me-1\"></i>Restaurant</span>\n");
      out.write("                        </div>\n");
      out.write("                    </div>\n");
      out.write("                </div>\n");
      out.write("            </div>\n");
      out.write("\n");
      out.write("            <!-- Accommodation 3 -->\n");
      out.write("            <div class=\"col-md-6\">\n");
      out.write("                <div class=\"feature-card\">\n");
      out.write("                    <img src=\"https://picsum.photos/seed/kampung-kuantan-homestay/700/400\"\n");
      out.write("                         alt=\"Kampung Kuantan Riverside Homestay\">\n");
      out.write("                    <div class=\"card-body\">\n");
      out.write("                        <div class=\"card-badge\"><i class=\"fas fa-home me-1\"></i>Homestay</div>\n");
      out.write("                        <h4 class=\"card-title\">Kampung Kuantan Riverside Homestay</h4>\n");
      out.write("                        <p class=\"card-text\">\n");
      out.write("                            Experience authentic Malay village hospitality at this traditional riverside\n");
      out.write("                            homestay in Kampung Kuantan — ground zero for the firefly experience.\n");
      out.write("                            Wake up to the gentle sound of the Selangor River, enjoy home-cooked local\n");
      out.write("                            meals, and step directly onto a boat for your evening firefly cruise.\n");
      out.write("                            An affordable and immersive way to connect with local culture.\n");
      out.write("                        </p>\n");
      out.write("                        <div class=\"mt-3 d-flex gap-3 flex-wrap\">\n");
      out.write("                            <span class=\"text-muted small\"><i class=\"fas fa-tag me-1\"></i>From RM 70/night</span>\n");
      out.write("                            <span class=\"text-muted small\"><i class=\"fas fa-utensils me-1\"></i>Meals included</span>\n");
      out.write("                            <span class=\"text-muted small\"><i class=\"fas fa-leaf me-1\"></i>Eco-friendly</span>\n");
      out.write("                        </div>\n");
      out.write("                    </div>\n");
      out.write("                </div>\n");
      out.write("            </div>\n");
      out.write("\n");
      out.write("            <!-- Accommodation 4 -->\n");
      out.write("            <div class=\"col-md-6\">\n");
      out.write("                <div class=\"feature-card\">\n");
      out.write("                    <img src=\"https://picsum.photos/seed/bukit-melawati-chalet/700/400\"\n");
      out.write("                         alt=\"Bukit Melawati Chalet\">\n");
      out.write("                    <div class=\"card-body\">\n");
      out.write("                        <div class=\"card-badge\"><i class=\"fas fa-mountain me-1\"></i>Hillside Chalet</div>\n");
      out.write("                        <h4 class=\"card-title\">Bukit Melawati Chalet</h4>\n");
      out.write("                        <p class=\"card-text\">\n");
      out.write("                            Perched on the slopes of Bukit Melawati, these charming wooden chalets\n");
      out.write("                            offer sweeping views of the Straits of Malacca and the Selangor River\n");
      out.write("                            estuary. The property is surrounded by nature park greenery and is home\n");
      out.write("                            to the resident silver leaf monkey population. Enjoy cool hilltop breezes,\n");
      out.write("                            a quiet atmosphere, and easy access to all of Bukit Melawati's heritage\n");
      out.write("                            attractions.\n");
      out.write("                        </p>\n");
      out.write("                        <div class=\"mt-3 d-flex gap-3 flex-wrap\">\n");
      out.write("                            <span class=\"text-muted small\"><i class=\"fas fa-tag me-1\"></i>From RM 95/night</span>\n");
      out.write("                            <span class=\"text-muted small\"><i class=\"fas fa-mountain me-1\"></i>Hilltop views</span>\n");
      out.write("                            <span class=\"text-muted small\"><i class=\"fas fa-paw me-1\"></i>Wildlife nearby</span>\n");
      out.write("                        </div>\n");
      out.write("                    </div>\n");
      out.write("                </div>\n");
      out.write("            </div>\n");
      out.write("\n");
      out.write("        </div>\n");
      out.write("\n");
      out.write("        <div class=\"text-center mt-5\">\n");
      out.write("            <a href=\"https://maps.app.goo.gl/1dABwi35VsLAE8EU9\" target=\"_blank\" class=\"maps-link-btn me-3\">\n");
      out.write("                <i class=\"fab fa-google me-1\"></i>Find on Google Maps\n");
      out.write("            </a>\n");
      out.write("            <a href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/contact.jsp\" class=\"btn-primary-custom btn\">\n");
      out.write("                Ask About Accommodation\n");
      out.write("            </a>\n");
      out.write("        </div>\n");
      out.write("    </div>\n");
      out.write("</section>\n");
      out.write("\n");
      out.write("<footer>\n");
      out.write("    <div class=\"footer-stripe\"></div>\n");
      out.write("    <div class=\"footer-body\">\n");
      out.write("        <div class=\"container d-flex flex-column flex-md-row align-items-center justify-content-between gap-2\">\n");
      out.write("            <img src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/images/vm2026/logo.png\"\n");
      out.write("                 alt=\"Visit Malaysia 2026\" style=\"height:36px; opacity:0.85;\">\n");
      out.write("            <p class=\"mb-0\">&copy; 2026 Kuala Selangor Tourism &mdash; CSC584 Individual Assignment</p>\n");
      out.write("            <a href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/developer.jsp\">Developer Info</a>\n");
      out.write("        </div>\n");
      out.write("    </div>\n");
      out.write("</footer>\n");
      out.write("\n");
      out.write("<script src=\"https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/js/bootstrap.bundle.min.js\"></script>\n");
      out.write("</body>\n");
      out.write("</html>\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof jakarta.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
