/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: jetty/12.0.21
 * Generated at: 2026-06-30 06:26:47 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import jakarta.servlet.*;
import jakarta.servlet.http.*;
import jakarta.servlet.jsp.*;

public final class activities_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports,
                 org.apache.jasper.runtime.JspSourceDirectives {

  private static final jakarta.servlet.jsp.JspFactory _jspxFactory =
          jakarta.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(1);
    _jspx_dependants.put("/WEB-INF/includes/nav.jsp", Long.valueOf(1782799811895L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.LinkedHashSet<>(4);
    _jspx_imports_packages.add("jakarta.servlet");
    _jspx_imports_packages.add("jakarta.servlet.http");
    _jspx_imports_packages.add("jakarta.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile jakarta.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public boolean getErrorOnELNotFound() {
    return false;
  }

  public jakarta.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final jakarta.servlet.http.HttpServletRequest request, final jakarta.servlet.http.HttpServletResponse response)
      throws java.io.IOException, jakarta.servlet.ServletException {

    if (!jakarta.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final jakarta.servlet.jsp.PageContext pageContext;
    jakarta.servlet.http.HttpSession session = null;
    final jakarta.servlet.ServletContext application;
    final jakarta.servlet.ServletConfig config;
    jakarta.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    jakarta.servlet.jsp.JspWriter _jspx_out = null;
    jakarta.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\n");
      out.write("<!DOCTYPE html>\n");
      out.write("<html lang=\"en\">\n");
      out.write("<head>\n");
      out.write("    <meta charset=\"UTF-8\">\n");
      out.write("    <meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">\n");
      out.write("    <title>Activities — Kuala Selangor Tourism</title>\n");
      out.write("    <link rel=\"stylesheet\" href=\"https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css\">\n");
      out.write("    <link rel=\"stylesheet\" href=\"https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.5.0/css/all.min.css\">\n");
      out.write("    <link rel=\"stylesheet\" href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/css/style.css\">\n");
      out.write("</head>\n");
      out.write("<body>\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("<nav class=\"navbar navbar-expand-lg\">\n");
      out.write("    <div class=\"container\">\n");
      out.write("        <a class=\"navbar-brand\" href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/index.jsp\">\n");
      out.write("            <img src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/images/vm2026/logo.png\"\n");
      out.write("                 alt=\"Visit Malaysia 2026\"\n");
      out.write("                 class=\"vm-logo\">\n");
      out.write("            <span class=\"brand-sep\"></span>\n");
      out.write("            <span class=\"brand-name\">Kuala <span>Selangor</span></span>\n");
      out.write("        </a>\n");
      out.write("        <button class=\"navbar-toggler\" type=\"button\" data-bs-toggle=\"collapse\"\n");
      out.write("                data-bs-target=\"#mainNav\" aria-controls=\"mainNav\"\n");
      out.write("                aria-expanded=\"false\" aria-label=\"Toggle navigation\">\n");
      out.write("            <span class=\"navbar-toggler-icon\"></span>\n");
      out.write("        </button>\n");
      out.write("        <div class=\"collapse navbar-collapse\" id=\"mainNav\">\n");
      out.write("            <ul class=\"navbar-nav ms-auto\">\n");
      out.write("                <li class=\"nav-item\">\n");
      out.write("                    <a class=\"nav-link\" href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/index.jsp\">Home</a>\n");
      out.write("                </li>\n");
      out.write("                <li class=\"nav-item\">\n");
      out.write("                    <a class=\"nav-link\" href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/gallery.jsp\">Gallery</a>\n");
      out.write("                </li>\n");
      out.write("                <li class=\"nav-item\">\n");
      out.write("                    <a class=\"nav-link\" href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/activities.jsp\">Activities</a>\n");
      out.write("                </li>\n");
      out.write("                <li class=\"nav-item\">\n");
      out.write("                    <a class=\"nav-link\" href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/accommodation.jsp\">Accommodation</a>\n");
      out.write("                </li>\n");
      out.write("                <li class=\"nav-item\">\n");
      out.write("                    <a class=\"nav-link\" href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/contact.jsp\">Contact</a>\n");
      out.write("                </li>\n");
      out.write("                <li class=\"nav-item\">\n");
      out.write("                    <a class=\"nav-link\" href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/developer.jsp\">Developer</a>\n");
      out.write("                </li>\n");
      out.write("            </ul>\n");
      out.write("        </div>\n");
      out.write("    </div>\n");
      out.write("</nav>\n");
      out.write("<div class=\"vm-stripe\"></div>\n");
      out.write("\n");
      out.write("\n");
      out.write("<div class=\"page-header\">\n");
      out.write("    <h1>Things To Do</h1>\n");
      out.write("    <p>4 unforgettable experiences in Kuala Selangor</p>\n");
      out.write("</div>\n");
      out.write("\n");
      out.write("<section class=\"section-padding\">\n");
      out.write("    <div class=\"container\">\n");
      out.write("        <div class=\"text-center mb-5\">\n");
      out.write("            <h2 class=\"section-title\">Top Activities</h2>\n");
      out.write("            <hr class=\"title-divider mx-auto\">\n");
      out.write("            <p class=\"section-subtitle\">From natural wonders to cultural heritage — there's something for everyone</p>\n");
      out.write("        </div>\n");
      out.write("\n");
      out.write("        <div class=\"row g-4\">\n");
      out.write("\n");
      out.write("            <!-- Activity 1: Sky Mirror -->\n");
      out.write("            <div class=\"col-md-6\">\n");
      out.write("                <div class=\"feature-card\">\n");
      out.write("                    <img src=\"https://picsum.photos/seed/sky-mirror-activity/700/400\"\n");
      out.write("                         alt=\"Sky Mirror Experience\">\n");
      out.write("                    <div class=\"card-body\">\n");
      out.write("                        <div class=\"card-badge\"><i class=\"fas fa-water me-1\"></i>Natural Wonder</div>\n");
      out.write("                        <h4 class=\"card-title\">Sky Mirror Experience</h4>\n");
      out.write("                        <p class=\"card-text\">\n");
      out.write("                            Visit the famous Sasaran sandbar — one of Malaysia's most jaw-dropping\n");
      out.write("                            natural spectacles. During low tide, a vast stretch of flat sand emerges\n");
      out.write("                            from the sea and creates a perfect mirror reflection of the sky, clouds,\n");
      out.write("                            and horizon. Reachable by a short boat ride from Pasir Penambang jetty,\n");
      out.write("                            the Sky Mirror is available twice a month and is an absolute must-visit\n");
      out.write("                            for photographers and nature lovers alike.\n");
      out.write("                        </p>\n");
      out.write("                        <div class=\"mt-3 d-flex gap-3 flex-wrap\">\n");
      out.write("                            <span class=\"text-muted small\"><i class=\"fas fa-clock me-1\"></i>2–3 hours</span>\n");
      out.write("                            <span class=\"text-muted small\"><i class=\"fas fa-users me-1\"></i>All ages</span>\n");
      out.write("                            <span class=\"text-muted small\"><i class=\"fas fa-calendar me-1\"></i>Twice monthly</span>\n");
      out.write("                        </div>\n");
      out.write("                    </div>\n");
      out.write("                </div>\n");
      out.write("            </div>\n");
      out.write("\n");
      out.write("            <!-- Activity 2: Fireflies River Cruise -->\n");
      out.write("            <div class=\"col-md-6\">\n");
      out.write("                <div class=\"feature-card\">\n");
      out.write("                    <img src=\"https://picsum.photos/seed/fireflies-river-cruise/700/400\"\n");
      out.write("                         alt=\"Fireflies River Cruise\">\n");
      out.write("                    <div class=\"card-body\">\n");
      out.write("                        <div class=\"card-badge\"><i class=\"fas fa-star me-1\"></i>Night Experience</div>\n");
      out.write("                        <h4 class=\"card-title\">Fireflies River Cruise</h4>\n");
      out.write("                        <p class=\"card-text\">\n");
      out.write("                            Embark on a magical boat ride along the Selangor River after dark to witness\n");
      out.write("                            thousands of synchronised fireflies (Pteroptyx tener) glowing in perfect\n");
      out.write("                            unison along the mangrove trees. Kampung Kuantan is home to one of the\n");
      out.write("                            largest and most accessible firefly habitats in the world. The mesmerising\n");
      out.write("                            natural light show is best enjoyed on a moonless night from September\n");
      out.write("                            to February.\n");
      out.write("                        </p>\n");
      out.write("                        <div class=\"mt-3 d-flex gap-3 flex-wrap\">\n");
      out.write("                            <span class=\"text-muted small\"><i class=\"fas fa-clock me-1\"></i>1–1.5 hours</span>\n");
      out.write("                            <span class=\"text-muted small\"><i class=\"fas fa-moon me-1\"></i>Night only</span>\n");
      out.write("                            <span class=\"text-muted small\"><i class=\"fas fa-users me-1\"></i>Families welcome</span>\n");
      out.write("                        </div>\n");
      out.write("                    </div>\n");
      out.write("                </div>\n");
      out.write("            </div>\n");
      out.write("\n");
      out.write("            <!-- Activity 3: Bukit Melawati Heritage Walk -->\n");
      out.write("            <div class=\"col-md-6\">\n");
      out.write("                <div class=\"feature-card\">\n");
      out.write("                    <img src=\"https://picsum.photos/seed/bukit-melawati-heritage/700/400\"\n");
      out.write("                         alt=\"Bukit Melawati Heritage Walk\">\n");
      out.write("                    <div class=\"card-body\">\n");
      out.write("                        <div class=\"card-badge\"><i class=\"fas fa-landmark me-1\"></i>History & Culture</div>\n");
      out.write("                        <h4 class=\"card-title\">Bukit Melawati Heritage Walk</h4>\n");
      out.write("                        <p class=\"card-text\">\n");
      out.write("                            Explore the hilltop of Bukit Melawati, the original seat of the Selangor\n");
      out.write("                            Sultanate. Visit the Altingsburg Lighthouse, the historic Dutch fort ruins,\n");
      out.write("                            and the Kuala Selangor Nature Park. Along the way, you'll encounter friendly\n");
      out.write("                            silver leaf monkeys (Presbytis cristata) that roam freely. The hilltop\n");
      out.write("                            offers panoramic views of the Straits of Malacca and the surrounding\n");
      out.write("                            river estuary.\n");
      out.write("                        </p>\n");
      out.write("                        <div class=\"mt-3 d-flex gap-3 flex-wrap\">\n");
      out.write("                            <span class=\"text-muted small\"><i class=\"fas fa-clock me-1\"></i>2–4 hours</span>\n");
      out.write("                            <span class=\"text-muted small\"><i class=\"fas fa-sun me-1\"></i>Daytime</span>\n");
      out.write("                            <span class=\"text-muted small\"><i class=\"fas fa-ticket me-1\"></i>Free entry</span>\n");
      out.write("                        </div>\n");
      out.write("                    </div>\n");
      out.write("                </div>\n");
      out.write("            </div>\n");
      out.write("\n");
      out.write("            <!-- Activity 4: Seafood Dining -->\n");
      out.write("            <div class=\"col-md-6\">\n");
      out.write("                <div class=\"feature-card\">\n");
      out.write("                    <img src=\"https://picsum.photos/seed/kuala-selangor-crab-seafood/700/400\"\n");
      out.write("                         alt=\"Seafood Dining Experience\">\n");
      out.write("                    <div class=\"card-body\">\n");
      out.write("                        <div class=\"card-badge\"><i class=\"fas fa-fish me-1\"></i>Food & Dining</div>\n");
      out.write("                        <h4 class=\"card-title\">Seafood Dining Experience</h4>\n");
      out.write("                        <p class=\"card-text\">\n");
      out.write("                            No visit to Kuala Selangor is complete without indulging in the legendary\n");
      out.write("                            fresh seafood. Head to Pasir Penambang or the town waterfront where dozens\n");
      out.write("                            of Chinese seafood restaurants serve freshly caught mud crab, prawns, and\n");
      out.write("                            fish. The signature dish is chilli crab — meaty and flavourful, cooked in\n");
      out.write("                            a rich, tangy sauce. Dining here at sunset with views of the river estuary\n");
      out.write("                            is an experience unlike any other.\n");
      out.write("                        </p>\n");
      out.write("                        <div class=\"mt-3 d-flex gap-3 flex-wrap\">\n");
      out.write("                            <span class=\"text-muted small\"><i class=\"fas fa-clock me-1\"></i>1–2 hours</span>\n");
      out.write("                            <span class=\"text-muted small\"><i class=\"fas fa-utensils me-1\"></i>Lunch &amp; Dinner</span>\n");
      out.write("                            <span class=\"text-muted small\"><i class=\"fas fa-dollar-sign me-1\"></i>RM 30–80 per pax</span>\n");
      out.write("                        </div>\n");
      out.write("                    </div>\n");
      out.write("                </div>\n");
      out.write("            </div>\n");
      out.write("\n");
      out.write("        </div>\n");
      out.write("\n");
      out.write("        <div class=\"text-center mt-5\">\n");
      out.write("            <a href=\"https://maps.app.goo.gl/1dABwi35VsLAE8EU9\" target=\"_blank\" class=\"maps-link-btn me-3\">\n");
      out.write("                <i class=\"fab fa-google me-1\"></i>Find Activities on Maps\n");
      out.write("            </a>\n");
      out.write("            <a href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/contact.jsp\" class=\"btn-primary-custom btn\">\n");
      out.write("                Enquire Now\n");
      out.write("            </a>\n");
      out.write("        </div>\n");
      out.write("    </div>\n");
      out.write("</section>\n");
      out.write("\n");
      out.write("<footer>\n");
      out.write("    <div class=\"footer-stripe\"></div>\n");
      out.write("    <div class=\"footer-body\">\n");
      out.write("        <div class=\"container d-flex flex-column flex-md-row align-items-center justify-content-between gap-2\">\n");
      out.write("            <img src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/images/vm2026/logo.png\"\n");
      out.write("                 alt=\"Visit Malaysia 2026\" style=\"height:36px; opacity:0.85;\">\n");
      out.write("            <p class=\"mb-0\">&copy; 2026 Kuala Selangor Tourism &mdash; CSC584 Individual Assignment</p>\n");
      out.write("            <a href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/developer.jsp\">Developer Info</a>\n");
      out.write("        </div>\n");
      out.write("    </div>\n");
      out.write("</footer>\n");
      out.write("\n");
      out.write("<script src=\"https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/js/bootstrap.bundle.min.js\"></script>\n");
      out.write("</body>\n");
      out.write("</html>\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof jakarta.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
