/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: jetty/12.0.21
 * Generated at: 2026-06-30 06:26:49 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import jakarta.servlet.*;
import jakarta.servlet.http.*;
import jakarta.servlet.jsp.*;

public final class contact_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports,
                 org.apache.jasper.runtime.JspSourceDirectives {

  private static final jakarta.servlet.jsp.JspFactory _jspxFactory =
          jakarta.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(1);
    _jspx_dependants.put("/WEB-INF/includes/nav.jsp", Long.valueOf(1782799811895L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.LinkedHashSet<>(4);
    _jspx_imports_packages.add("jakarta.servlet");
    _jspx_imports_packages.add("jakarta.servlet.http");
    _jspx_imports_packages.add("jakarta.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile jakarta.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public boolean getErrorOnELNotFound() {
    return false;
  }

  public jakarta.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final jakarta.servlet.http.HttpServletRequest request, final jakarta.servlet.http.HttpServletResponse response)
      throws java.io.IOException, jakarta.servlet.ServletException {

    if (!jakarta.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final jakarta.servlet.jsp.PageContext pageContext;
    jakarta.servlet.http.HttpSession session = null;
    final jakarta.servlet.ServletContext application;
    final jakarta.servlet.ServletConfig config;
    jakarta.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    jakarta.servlet.jsp.JspWriter _jspx_out = null;
    jakarta.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\n");
      out.write("<!DOCTYPE html>\n");
      out.write("<html lang=\"en\">\n");
      out.write("<head>\n");
      out.write("    <meta charset=\"UTF-8\">\n");
      out.write("    <meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">\n");
      out.write("    <title>Contact & Inquiry — Kuala Selangor Tourism</title>\n");
      out.write("    <link rel=\"stylesheet\" href=\"https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css\">\n");
      out.write("    <link rel=\"stylesheet\" href=\"https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.5.0/css/all.min.css\">\n");
      out.write("    <link rel=\"stylesheet\" href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/css/style.css\">\n");
      out.write("</head>\n");
      out.write("<body>\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("<nav class=\"navbar navbar-expand-lg\">\n");
      out.write("    <div class=\"container\">\n");
      out.write("        <a class=\"navbar-brand\" href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/index.jsp\">\n");
      out.write("            <img src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/images/vm2026/logo.png\"\n");
      out.write("                 alt=\"Visit Malaysia 2026\"\n");
      out.write("                 class=\"vm-logo\">\n");
      out.write("            <span class=\"brand-sep\"></span>\n");
      out.write("            <span class=\"brand-name\">Kuala <span>Selangor</span></span>\n");
      out.write("        </a>\n");
      out.write("        <button class=\"navbar-toggler\" type=\"button\" data-bs-toggle=\"collapse\"\n");
      out.write("                data-bs-target=\"#mainNav\" aria-controls=\"mainNav\"\n");
      out.write("                aria-expanded=\"false\" aria-label=\"Toggle navigation\">\n");
      out.write("            <span class=\"navbar-toggler-icon\"></span>\n");
      out.write("        </button>\n");
      out.write("        <div class=\"collapse navbar-collapse\" id=\"mainNav\">\n");
      out.write("            <ul class=\"navbar-nav ms-auto\">\n");
      out.write("                <li class=\"nav-item\">\n");
      out.write("                    <a class=\"nav-link\" href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/index.jsp\">Home</a>\n");
      out.write("                </li>\n");
      out.write("                <li class=\"nav-item\">\n");
      out.write("                    <a class=\"nav-link\" href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/gallery.jsp\">Gallery</a>\n");
      out.write("                </li>\n");
      out.write("                <li class=\"nav-item\">\n");
      out.write("                    <a class=\"nav-link\" href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/activities.jsp\">Activities</a>\n");
      out.write("                </li>\n");
      out.write("                <li class=\"nav-item\">\n");
      out.write("                    <a class=\"nav-link\" href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/accommodation.jsp\">Accommodation</a>\n");
      out.write("                </li>\n");
      out.write("                <li class=\"nav-item\">\n");
      out.write("                    <a class=\"nav-link\" href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/contact.jsp\">Contact</a>\n");
      out.write("                </li>\n");
      out.write("                <li class=\"nav-item\">\n");
      out.write("                    <a class=\"nav-link\" href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/developer.jsp\">Developer</a>\n");
      out.write("                </li>\n");
      out.write("            </ul>\n");
      out.write("        </div>\n");
      out.write("    </div>\n");
      out.write("</nav>\n");
      out.write("<div class=\"vm-stripe\"></div>\n");
      out.write("\n");
      out.write("\n");
      out.write("<div class=\"page-header\">\n");
      out.write("    <h1>Contact Us</h1>\n");
      out.write("    <p>Send us an inquiry — we're happy to help plan your visit</p>\n");
      out.write("</div>\n");
      out.write("\n");
      out.write("<section class=\"section-padding contact-section\">\n");
      out.write("    <div class=\"container\">\n");
      out.write("        <div class=\"row g-5 align-items-start justify-content-center\">\n");
      out.write("\n");
      out.write("            <!-- Sidebar Info -->\n");
      out.write("            <div class=\"col-lg-4\">\n");
      out.write("                <div class=\"mb-4\">\n");
      out.write("                    <h4 class=\"fw-bold text-primary-custom mb-3\">Get In Touch</h4>\n");
      out.write("                    <p class=\"text-muted\" style=\"line-height:1.8;\">\n");
      out.write("                        Have questions about visiting Kuala Selangor or the Sky Mirror? Send us\n");
      out.write("                        an inquiry and our team will get back to you as soon as possible.\n");
      out.write("                    </p>\n");
      out.write("                </div>\n");
      out.write("                <ul class=\"list-unstyled\">\n");
      out.write("                    <li class=\"d-flex gap-3 mb-3\">\n");
      out.write("                        <div style=\"min-width:36px; height:36px; background:var(--primary); border-radius:50%; display:flex; align-items:center; justify-content:center;\">\n");
      out.write("                            <i class=\"fas fa-map-marker-alt text-white\" style=\"font-size:0.85rem;\"></i>\n");
      out.write("                        </div>\n");
      out.write("                        <div>\n");
      out.write("                            <p class=\"fw-semibold mb-0\">Location</p>\n");
      out.write("                            <p class=\"text-muted small mb-0\">Kuala Selangor, Selangor, Malaysia</p>\n");
      out.write("                        </div>\n");
      out.write("                    </li>\n");
      out.write("                    <li class=\"d-flex gap-3 mb-3\">\n");
      out.write("                        <div style=\"min-width:36px; height:36px; background:var(--primary); border-radius:50%; display:flex; align-items:center; justify-content:center;\">\n");
      out.write("                            <i class=\"fas fa-envelope text-white\" style=\"font-size:0.85rem;\"></i>\n");
      out.write("                        </div>\n");
      out.write("                        <div>\n");
      out.write("                            <p class=\"fw-semibold mb-0\">Email</p>\n");
      out.write("                            <p class=\"text-muted small mb-0\">info@kuala-selangor-tourism.com</p>\n");
      out.write("                        </div>\n");
      out.write("                    </li>\n");
      out.write("                    <li class=\"d-flex gap-3 mb-3\">\n");
      out.write("                        <div style=\"min-width:36px; height:36px; background:var(--primary); border-radius:50%; display:flex; align-items:center; justify-content:center;\">\n");
      out.write("                            <i class=\"fas fa-phone text-white\" style=\"font-size:0.85rem;\"></i>\n");
      out.write("                        </div>\n");
      out.write("                        <div>\n");
      out.write("                            <p class=\"fw-semibold mb-0\">Phone</p>\n");
      out.write("                            <p class=\"text-muted small mb-0\">+60 3-3289 0000</p>\n");
      out.write("                        </div>\n");
      out.write("                    </li>\n");
      out.write("                </ul>\n");
      out.write("                <div class=\"mt-4\">\n");
      out.write("                    <a href=\"https://maps.app.goo.gl/kuala-selangor\" target=\"_blank\" class=\"maps-link-btn w-100 justify-content-center\">\n");
      out.write("                        <i class=\"fab fa-google\"></i> Open in Google Maps\n");
      out.write("                    </a>\n");
      out.write("                </div>\n");
      out.write("            </div>\n");
      out.write("\n");
      out.write("            <!-- Inquiry Form -->\n");
      out.write("            <div class=\"col-lg-7\">\n");
      out.write("                <div class=\"inquiry-form-card\">\n");
      out.write("                    <h4 class=\"fw-bold text-primary-custom mb-4\">\n");
      out.write("                        <i class=\"fas fa-paper-plane me-2\"></i>Visitor Inquiry Form\n");
      out.write("                    </h4>\n");
      out.write("\n");
      out.write("                    ");
      out.write("\n");
      out.write("                    ");
 if (request.getAttribute("success") != null) { 
      out.write("\n");
      out.write("                        <div class=\"alert-success-custom\">\n");
      out.write("                            <i class=\"fas fa-check-circle me-2\"></i>");
      out.print( request.getAttribute("success") );
      out.write("\n");
      out.write("                        </div>\n");
      out.write("                    ");
 } 
      out.write("\n");
      out.write("                    ");
 if (request.getAttribute("error") != null) { 
      out.write("\n");
      out.write("                        <div class=\"alert-error-custom\">\n");
      out.write("                            <i class=\"fas fa-exclamation-circle me-2\"></i>");
      out.print( request.getAttribute("error") );
      out.write("\n");
      out.write("                        </div>\n");
      out.write("                    ");
 } 
      out.write("\n");
      out.write("\n");
      out.write("                    <form id=\"inquiryForm\" action=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/submit-inquiry\"\n");
      out.write("                          method=\"post\" novalidate onsubmit=\"return validateForm()\">\n");
      out.write("\n");
      out.write("                        <div class=\"row g-3\">\n");
      out.write("                            <!-- Name -->\n");
      out.write("                            <div class=\"col-md-6\">\n");
      out.write("                                <label for=\"name\" class=\"form-label\">Full Name <span class=\"text-danger\">*</span></label>\n");
      out.write("                                <input type=\"text\" id=\"name\" name=\"name\" class=\"form-control\"\n");
      out.write("                                       placeholder=\"e.g. Ahmad Bin Ali\" required\n");
      out.write("                                       value=\"");
      out.print( request.getParameter("name") != null ? request.getParameter("name") : "" );
      out.write("\">\n");
      out.write("                            </div>\n");
      out.write("\n");
      out.write("                            <!-- Contact Number -->\n");
      out.write("                            <div class=\"col-md-6\">\n");
      out.write("                                <label for=\"contactNumber\" class=\"form-label\">Contact Number <span class=\"text-danger\">*</span></label>\n");
      out.write("                                <input type=\"tel\" id=\"contactNumber\" name=\"contactNumber\" class=\"form-control\"\n");
      out.write("                                       placeholder=\"e.g. 012-3456789\" required\n");
      out.write("                                       value=\"");
      out.print( request.getParameter("contactNumber") != null ? request.getParameter("contactNumber") : "" );
      out.write("\">\n");
      out.write("                            </div>\n");
      out.write("\n");
      out.write("                            <!-- Gender -->\n");
      out.write("                            <div class=\"col-md-6\">\n");
      out.write("                                <label for=\"gender\" class=\"form-label\">Gender <span class=\"text-danger\">*</span></label>\n");
      out.write("                                <select id=\"gender\" name=\"gender\" class=\"form-select\" required>\n");
      out.write("                                    <option value=\"\" disabled\n");
      out.write("                                        ");
      out.print( (request.getParameter("gender") == null) ? "selected" : "" );
      out.write(">\n");
      out.write("                                        Select gender\n");
      out.write("                                    </option>\n");
      out.write("                                    <option value=\"Male\"\n");
      out.write("                                        ");
      out.print( "Male".equals(request.getParameter("gender")) ? "selected" : "" );
      out.write(">Male</option>\n");
      out.write("                                    <option value=\"Female\"\n");
      out.write("                                        ");
      out.print( "Female".equals(request.getParameter("gender")) ? "selected" : "" );
      out.write(">Female</option>\n");
      out.write("                                    <option value=\"Prefer not to say\"\n");
      out.write("                                        ");
      out.print( "Prefer not to say".equals(request.getParameter("gender")) ? "selected" : "" );
      out.write(">Prefer not to say</option>\n");
      out.write("                                </select>\n");
      out.write("                            </div>\n");
      out.write("\n");
      out.write("                            <!-- Email -->\n");
      out.write("                            <div class=\"col-md-6\">\n");
      out.write("                                <label for=\"email\" class=\"form-label\">Email Address <span class=\"text-danger\">*</span></label>\n");
      out.write("                                <input type=\"email\" id=\"email\" name=\"email\" class=\"form-control\"\n");
      out.write("                                       placeholder=\"e.g. ahmad@email.com\" required\n");
      out.write("                                       value=\"");
      out.print( request.getParameter("email") != null ? request.getParameter("email") : "" );
      out.write("\">\n");
      out.write("                            </div>\n");
      out.write("\n");
      out.write("                            <!-- How did you know about us -->\n");
      out.write("                            <div class=\"col-12\">\n");
      out.write("                                <label for=\"howHeard\" class=\"form-label\">How did you know about us? <span class=\"text-danger\">*</span></label>\n");
      out.write("                                <select id=\"howHeard\" name=\"howHeard\" class=\"form-select\" required>\n");
      out.write("                                    <option value=\"\" disabled\n");
      out.write("                                        ");
      out.print( (request.getParameter("howHeard") == null) ? "selected" : "" );
      out.write(">\n");
      out.write("                                        Please select an option\n");
      out.write("                                    </option>\n");
      out.write("                                    <option value=\"Social Media\"\n");
      out.write("                                        ");
      out.print( "Social Media".equals(request.getParameter("howHeard")) ? "selected" : "" );
      out.write(">Social Media</option>\n");
      out.write("                                    <option value=\"Search Engine\"\n");
      out.write("                                        ");
      out.print( "Search Engine".equals(request.getParameter("howHeard")) ? "selected" : "" );
      out.write(">Search Engine (Google, Bing, etc.)</option>\n");
      out.write("                                    <option value=\"Friends or Family\"\n");
      out.write("                                        ");
      out.print( "Friends or Family".equals(request.getParameter("howHeard")) ? "selected" : "" );
      out.write(">Friends or Family</option>\n");
      out.write("                                    <option value=\"Travel Magazine\"\n");
      out.write("                                        ");
      out.print( "Travel Magazine".equals(request.getParameter("howHeard")) ? "selected" : "" );
      out.write(">Travel Magazine / Blog</option>\n");
      out.write("                                    <option value=\"Television or Radio\"\n");
      out.write("                                        ");
      out.print( "Television or Radio".equals(request.getParameter("howHeard")) ? "selected" : "" );
      out.write(">Television or Radio</option>\n");
      out.write("                                    <option value=\"Other\"\n");
      out.write("                                        ");
      out.print( "Other".equals(request.getParameter("howHeard")) ? "selected" : "" );
      out.write(">Other</option>\n");
      out.write("                                </select>\n");
      out.write("                            </div>\n");
      out.write("\n");
      out.write("                            <!-- Message -->\n");
      out.write("                            <div class=\"col-12\">\n");
      out.write("                                <label for=\"message\" class=\"form-label\">Message <span class=\"text-danger\">*</span></label>\n");
      out.write("                                <textarea id=\"message\" name=\"message\" class=\"form-control\"\n");
      out.write("                                          rows=\"4\" placeholder=\"Tell us what you'd like to know...\" required>");
      out.print( request.getParameter("message") != null ? request.getParameter("message") : "" );
      out.write("</textarea>\n");
      out.write("                            </div>\n");
      out.write("                        </div>\n");
      out.write("\n");
      out.write("                        <div class=\"d-flex gap-3 mt-4\">\n");
      out.write("                            <button type=\"submit\" class=\"btn-primary-custom btn\">\n");
      out.write("                                <i class=\"fas fa-paper-plane me-2\"></i>Submit Inquiry\n");
      out.write("                            </button>\n");
      out.write("                            <button type=\"reset\" id=\"clearBtn\" class=\"btn-secondary-custom btn\">\n");
      out.write("                                <i class=\"fas fa-times me-2\"></i>Clear\n");
      out.write("                            </button>\n");
      out.write("                        </div>\n");
      out.write("                    </form>\n");
      out.write("                </div>\n");
      out.write("            </div>\n");
      out.write("\n");
      out.write("        </div>\n");
      out.write("    </div>\n");
      out.write("</section>\n");
      out.write("\n");
      out.write("<footer>\n");
      out.write("    <div class=\"footer-stripe\"></div>\n");
      out.write("    <div class=\"footer-body\">\n");
      out.write("        <div class=\"container d-flex flex-column flex-md-row align-items-center justify-content-between gap-2\">\n");
      out.write("            <img src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/images/vm2026/logo.png\"\n");
      out.write("                 alt=\"Visit Malaysia 2026\" style=\"height:36px; opacity:0.85;\">\n");
      out.write("            <p class=\"mb-0\">&copy; 2026 Kuala Selangor Tourism &mdash; CSC584 Individual Assignment</p>\n");
      out.write("            <a href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/developer.jsp\">Developer Info</a>\n");
      out.write("        </div>\n");
      out.write("    </div>\n");
      out.write("</footer>\n");
      out.write("\n");
      out.write("<script src=\"https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/js/bootstrap.bundle.min.js\"></script>\n");
      out.write("<script>\n");
      out.write("    function validateForm() {\n");
      out.write("        const fields = ['name', 'contactNumber', 'gender', 'email', 'howHeard', 'message'];\n");
      out.write("        for (const id of fields) {\n");
      out.write("            const el = document.getElementById(id);\n");
      out.write("            if (!el.value || el.value.trim() === '') {\n");
      out.write("                el.classList.add('is-invalid');\n");
      out.write("                el.focus();\n");
      out.write("                alert('Please fill in all required fields before submitting.');\n");
      out.write("                return false;\n");
      out.write("            } else {\n");
      out.write("                el.classList.remove('is-invalid');\n");
      out.write("            }\n");
      out.write("        }\n");
      out.write("        return true;\n");
      out.write("    }\n");
      out.write("\n");
      out.write("    // Clear invalid state on input\n");
      out.write("    document.querySelectorAll('.form-control, .form-select').forEach(el => {\n");
      out.write("        el.addEventListener('input', () => el.classList.remove('is-invalid'));\n");
      out.write("        el.addEventListener('change', () => el.classList.remove('is-invalid'));\n");
      out.write("    });\n");
      out.write("</script>\n");
      out.write("</body>\n");
      out.write("</html>\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof jakarta.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
