/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: jetty/12.0.21
 * Generated at: 2026-06-30 06:26:49 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import jakarta.servlet.*;
import jakarta.servlet.http.*;
import jakarta.servlet.jsp.*;

public final class developer_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports,
                 org.apache.jasper.runtime.JspSourceDirectives {

  private static final jakarta.servlet.jsp.JspFactory _jspxFactory =
          jakarta.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(1);
    _jspx_dependants.put("/WEB-INF/includes/nav.jsp", Long.valueOf(1782799811895L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.LinkedHashSet<>(4);
    _jspx_imports_packages.add("jakarta.servlet");
    _jspx_imports_packages.add("jakarta.servlet.http");
    _jspx_imports_packages.add("jakarta.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile jakarta.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public boolean getErrorOnELNotFound() {
    return false;
  }

  public jakarta.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final jakarta.servlet.http.HttpServletRequest request, final jakarta.servlet.http.HttpServletResponse response)
      throws java.io.IOException, jakarta.servlet.ServletException {

    if (!jakarta.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final jakarta.servlet.jsp.PageContext pageContext;
    jakarta.servlet.http.HttpSession session = null;
    final jakarta.servlet.ServletContext application;
    final jakarta.servlet.ServletConfig config;
    jakarta.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    jakarta.servlet.jsp.JspWriter _jspx_out = null;
    jakarta.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\n");
      out.write("<!DOCTYPE html>\n");
      out.write("<html lang=\"en\">\n");
      out.write("<head>\n");
      out.write("    <meta charset=\"UTF-8\">\n");
      out.write("    <meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">\n");
      out.write("    <title>Developer — Kuala Selangor Tourism</title>\n");
      out.write("    <link rel=\"stylesheet\" href=\"https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css\">\n");
      out.write("    <link rel=\"stylesheet\" href=\"https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.5.0/css/all.min.css\">\n");
      out.write("    <link rel=\"stylesheet\" href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/css/style.css\">\n");
      out.write("</head>\n");
      out.write("<body>\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("<nav class=\"navbar navbar-expand-lg\">\n");
      out.write("    <div class=\"container\">\n");
      out.write("        <a class=\"navbar-brand\" href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/index.jsp\">\n");
      out.write("            <img src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/images/vm2026/logo.png\"\n");
      out.write("                 alt=\"Visit Malaysia 2026\"\n");
      out.write("                 class=\"vm-logo\">\n");
      out.write("            <span class=\"brand-sep\"></span>\n");
      out.write("            <span class=\"brand-name\">Kuala <span>Selangor</span></span>\n");
      out.write("        </a>\n");
      out.write("        <button class=\"navbar-toggler\" type=\"button\" data-bs-toggle=\"collapse\"\n");
      out.write("                data-bs-target=\"#mainNav\" aria-controls=\"mainNav\"\n");
      out.write("                aria-expanded=\"false\" aria-label=\"Toggle navigation\">\n");
      out.write("            <span class=\"navbar-toggler-icon\"></span>\n");
      out.write("        </button>\n");
      out.write("        <div class=\"collapse navbar-collapse\" id=\"mainNav\">\n");
      out.write("            <ul class=\"navbar-nav ms-auto\">\n");
      out.write("                <li class=\"nav-item\">\n");
      out.write("                    <a class=\"nav-link\" href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/index.jsp\">Home</a>\n");
      out.write("                </li>\n");
      out.write("                <li class=\"nav-item\">\n");
      out.write("                    <a class=\"nav-link\" href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/gallery.jsp\">Gallery</a>\n");
      out.write("                </li>\n");
      out.write("                <li class=\"nav-item\">\n");
      out.write("                    <a class=\"nav-link\" href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/activities.jsp\">Activities</a>\n");
      out.write("                </li>\n");
      out.write("                <li class=\"nav-item\">\n");
      out.write("                    <a class=\"nav-link\" href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/accommodation.jsp\">Accommodation</a>\n");
      out.write("                </li>\n");
      out.write("                <li class=\"nav-item\">\n");
      out.write("                    <a class=\"nav-link\" href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/contact.jsp\">Contact</a>\n");
      out.write("                </li>\n");
      out.write("                <li class=\"nav-item\">\n");
      out.write("                    <a class=\"nav-link\" href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/developer.jsp\">Developer</a>\n");
      out.write("                </li>\n");
      out.write("            </ul>\n");
      out.write("        </div>\n");
      out.write("    </div>\n");
      out.write("</nav>\n");
      out.write("<div class=\"vm-stripe\"></div>\n");
      out.write("\n");
      out.write("\n");
      out.write("<div class=\"page-header\">\n");
      out.write("    <h1>Developer</h1>\n");
      out.write("    <p>About the developer behind this project</p>\n");
      out.write("</div>\n");
      out.write("\n");
      out.write("<section class=\"section-padding bg-light-custom\">\n");
      out.write("    <div class=\"container\">\n");
      out.write("        <div class=\"developer-card\">\n");
      out.write("\n");
      out.write("            <!-- Coloured Header Band -->\n");
      out.write("            <div class=\"developer-header\"></div>\n");
      out.write("\n");
      out.write("            <!-- Photo overlapping the header -->\n");
      out.write("            <div class=\"text-center\" style=\"margin-top: -70px; position:relative; z-index:2;\">\n");
      out.write("                ");
      out.write("\n");
      out.write("                <img src=\"./images/raef.png\"\n");
      out.write("                     alt=\"Developer Photo\"\n");
      out.write("                     class=\"developer-photo\">\n");
      out.write("            </div>\n");
      out.write("\n");
      out.write("            <div class=\"developer-body\">\n");
      out.write("                ");
      out.write("\n");
      out.write("                <h2 class=\"developer-name\">Raef Luqman Bin Mohammad Aidid</h2>\n");
      out.write("                <p class=\"developer-id\">Student ID: 2022673128</p>\n");
      out.write("\n");
      out.write("                <hr style=\"max-width:300px; margin:0 auto 1.5rem;\">\n");
      out.write("\n");
      out.write("                <ul class=\"contact-list\">\n");
      out.write("                    <li>\n");
      out.write("                        <i class=\"fas fa-id-badge\"></i>\n");
      out.write("                        <span><strong>Programme:</strong> CDCS230 Bachelor of Computer Science (Hons.)</span>\n");
      out.write("                    </li>\n");
      out.write("                    <li>\n");
      out.write("                        <i class=\"fas fa-university\"></i>\n");
      out.write("                        <span><strong>Institution:</strong> Universiti Teknologi MARA (UiTM)</span>\n");
      out.write("                    </li>\n");
      out.write("                    <li>\n");
      out.write("                        <i class=\"fas fa-envelope\"></i>\n");
      out.write("                        <span><strong>Email:</strong> <a href=\"mailto:2022673128@student.uitm.edu.my\">2022673128@student.uitm.edu.my</a></span>\n");
      out.write("                    </li>\n");
      out.write("                    <li>\n");
      out.write("                        <i class=\"fas fa-phone\"></i>\n");
      out.write("                        <span><strong>Phone:</strong> +60 10-936 4867</span>\n");
      out.write("                    </li>\n");
      out.write("                    <li>\n");
      out.write("                        <i class=\"fas fa-calendar-alt\"></i>\n");
      out.write("                        <span><strong>Semester:</strong> March 2026 &ndash; August 2026</span>\n");
      out.write("                    </li>\n");
      out.write("                    <li>\n");
      out.write("                        <i class=\"fas fa-laptop-code\"></i>\n");
      out.write("                        <span><strong>Assignment:</strong> Individual Assignment &mdash; Web Front-End Development (20%)</span>\n");
      out.write("                    </li>\n");
      out.write("                </ul>\n");
      out.write("\n");
      out.write("                <div class=\"mt-4 p-3 rounded-3\" style=\"background:var(--light-bg);\">\n");
      out.write("                    <h6 class=\"fw-bold text-primary-custom mb-2\">Tech Stack Used</h6>\n");
      out.write("                    <div class=\"d-flex flex-wrap gap-2 justify-content-center\">\n");
      out.write("                        <span class=\"badge\" style=\"background:var(--primary); font-size:0.85rem; padding:0.4rem 0.8rem;\">JSP</span>\n");
      out.write("                        <span class=\"badge\" style=\"background:var(--primary); font-size:0.85rem; padding:0.4rem 0.8rem;\">Java Servlets</span>\n");
      out.write("                        <span class=\"badge\" style=\"background:var(--primary); font-size:0.85rem; padding:0.4rem 0.8rem;\">JDBC</span>\n");
      out.write("                        <span class=\"badge\" style=\"background:var(--primary); font-size:0.85rem; padding:0.4rem 0.8rem;\">PostgreSQL</span>\n");
      out.write("                        <span class=\"badge\" style=\"background:var(--primary); font-size:0.85rem; padding:0.4rem 0.8rem;\">jQuery DataTables</span>\n");
      out.write("                        <span class=\"badge\" style=\"background:var(--secondary); font-size:0.85rem; padding:0.4rem 0.8rem;\">Bootstrap 5</span>\n");
      out.write("                        <span class=\"badge\" style=\"background:var(--secondary); font-size:0.85rem; padding:0.4rem 0.8rem;\">Apache Maven</span>\n");
      out.write("                        <span class=\"badge\" style=\"background:var(--secondary); font-size:0.85rem; padding:0.4rem 0.8rem;\">Jetty</span>\n");
      out.write("                    </div>\n");
      out.write("                </div>\n");
      out.write("            </div>\n");
      out.write("        </div>\n");
      out.write("    </div>\n");
      out.write("</section>\n");
      out.write("\n");
      out.write("<footer>\n");
      out.write("    <div class=\"footer-stripe\"></div>\n");
      out.write("    <div class=\"footer-body\">\n");
      out.write("        <div class=\"container d-flex flex-column flex-md-row align-items-center justify-content-between gap-2\">\n");
      out.write("            <img src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/images/vm2026/logo.png\"\n");
      out.write("                 alt=\"Visit Malaysia 2026\" style=\"height:36px; opacity:0.85;\">\n");
      out.write("            <p class=\"mb-0\">&copy; 2026 Kuala Selangor Tourism &mdash; CSC584 Individual Assignment</p>\n");
      out.write("            <a href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/developer.jsp\">Developer Info</a>\n");
      out.write("        </div>\n");
      out.write("    </div>\n");
      out.write("</footer>\n");
      out.write("\n");
      out.write("<script src=\"https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/js/bootstrap.bundle.min.js\"></script>\n");
      out.write("</body>\n");
      out.write("</html>\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof jakarta.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
