/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: jetty/12.0.21
 * Generated at: 2026-06-30 06:32:10 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import jakarta.servlet.*;
import jakarta.servlet.http.*;
import jakarta.servlet.jsp.*;

public final class index_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports,
                 org.apache.jasper.runtime.JspSourceDirectives {

  private static final jakarta.servlet.jsp.JspFactory _jspxFactory =
          jakarta.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(1);
    _jspx_dependants.put("/WEB-INF/includes/nav.jsp", Long.valueOf(1782799811895L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.LinkedHashSet<>(4);
    _jspx_imports_packages.add("jakarta.servlet");
    _jspx_imports_packages.add("jakarta.servlet.http");
    _jspx_imports_packages.add("jakarta.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile jakarta.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public boolean getErrorOnELNotFound() {
    return false;
  }

  public jakarta.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final jakarta.servlet.http.HttpServletRequest request, final jakarta.servlet.http.HttpServletResponse response)
      throws java.io.IOException, jakarta.servlet.ServletException {

    if (!jakarta.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final jakarta.servlet.jsp.PageContext pageContext;
    jakarta.servlet.http.HttpSession session = null;
    final jakarta.servlet.ServletContext application;
    final jakarta.servlet.ServletConfig config;
    jakarta.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    jakarta.servlet.jsp.JspWriter _jspx_out = null;
    jakarta.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\n");
      out.write("<!DOCTYPE html>\n");
      out.write("<html lang=\"en\">\n");
      out.write("<head>\n");
      out.write("    <meta charset=\"UTF-8\">\n");
      out.write("    <meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">\n");
      out.write("    <title>Kuala Selangor Tourism — Discover the Hidden Gem of Selangor</title>\n");
      out.write("    <link rel=\"stylesheet\" href=\"https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css\">\n");
      out.write("    <link rel=\"stylesheet\" href=\"https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.5.0/css/all.min.css\">\n");
      out.write("    <link rel=\"stylesheet\" href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/css/style.css\">\n");
      out.write("</head>\n");
      out.write("<body>\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("<nav class=\"navbar navbar-expand-lg\">\n");
      out.write("    <div class=\"container\">\n");
      out.write("        <a class=\"navbar-brand\" href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/index.jsp\">\n");
      out.write("            <img src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/images/vm2026/logo.png\"\n");
      out.write("                 alt=\"Visit Malaysia 2026\"\n");
      out.write("                 class=\"vm-logo\">\n");
      out.write("            <span class=\"brand-sep\"></span>\n");
      out.write("            <span class=\"brand-name\">Kuala <span>Selangor</span></span>\n");
      out.write("        </a>\n");
      out.write("        <button class=\"navbar-toggler\" type=\"button\" data-bs-toggle=\"collapse\"\n");
      out.write("                data-bs-target=\"#mainNav\" aria-controls=\"mainNav\"\n");
      out.write("                aria-expanded=\"false\" aria-label=\"Toggle navigation\">\n");
      out.write("            <span class=\"navbar-toggler-icon\"></span>\n");
      out.write("        </button>\n");
      out.write("        <div class=\"collapse navbar-collapse\" id=\"mainNav\">\n");
      out.write("            <ul class=\"navbar-nav ms-auto\">\n");
      out.write("                <li class=\"nav-item\">\n");
      out.write("                    <a class=\"nav-link\" href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/index.jsp\">Home</a>\n");
      out.write("                </li>\n");
      out.write("                <li class=\"nav-item\">\n");
      out.write("                    <a class=\"nav-link\" href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/gallery.jsp\">Gallery</a>\n");
      out.write("                </li>\n");
      out.write("                <li class=\"nav-item\">\n");
      out.write("                    <a class=\"nav-link\" href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/activities.jsp\">Activities</a>\n");
      out.write("                </li>\n");
      out.write("                <li class=\"nav-item\">\n");
      out.write("                    <a class=\"nav-link\" href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/accommodation.jsp\">Accommodation</a>\n");
      out.write("                </li>\n");
      out.write("                <li class=\"nav-item\">\n");
      out.write("                    <a class=\"nav-link\" href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/contact.jsp\">Contact</a>\n");
      out.write("                </li>\n");
      out.write("                <li class=\"nav-item\">\n");
      out.write("                    <a class=\"nav-link\" href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/developer.jsp\">Developer</a>\n");
      out.write("                </li>\n");
      out.write("            </ul>\n");
      out.write("        </div>\n");
      out.write("    </div>\n");
      out.write("</nav>\n");
      out.write("<div class=\"vm-stripe\"></div>\n");
      out.write("\n");
      out.write("\n");
      out.write("<!-- ===== HERO ===== -->\n");
      out.write("<section class=\"hero\">\n");
      out.write("    <div class=\"hero-overlay\"></div>\n");
      out.write("\n");
      out.write("    <div class=\"hero-content\">\n");
      out.write("        <div class=\"hero-badge\"><i class=\"fas fa-map-marker-alt\"></i> Selangor, Malaysia</div>\n");
      out.write("        <h1>Discover Kuala Selangor</h1>\n");
      out.write("        <p>Where the sky meets the sea. A tranquil coastal town famous for the magical Sky Mirror,\n");
      out.write("           enchanting fireflies, and rich Malay heritage.</p>\n");
      out.write("        <a href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/gallery.jsp\" class=\"btn btn-accent me-3\">Explore Gallery</a>\n");
      out.write("        <a href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/contact.jsp\" class=\"btn btn-outline-light\">Plan Your Visit</a>\n");
      out.write("    </div>\n");
      out.write("\n");
      out.write("    ");
      out.write("\n");
      out.write("    <img src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/images/vm2026/sunbear-male.png\"\n");
      out.write("         alt=\"Mao — Visit Malaysia 2026 Sun Bear Mascot\"\n");
      out.write("         class=\"hero-mascot\">\n");
      out.write("</section>\n");
      out.write("\n");
      out.write("<!-- ===== INFO STRIP ===== -->\n");
      out.write("<section class=\"info-strip\">\n");
      out.write("    <div class=\"container\">\n");
      out.write("        <div class=\"row g-4 justify-content-center\">\n");
      out.write("            <div class=\"col-sm-6 col-md-3\">\n");
      out.write("                <div class=\"info-card\">\n");
      out.write("                    <i class=\"fas fa-water\"></i>\n");
      out.write("                    <h5>Sky Mirror</h5>\n");
      out.write("                    <p>A natural tidal flat phenomenon that creates breathtaking mirror reflections</p>\n");
      out.write("                </div>\n");
      out.write("            </div>\n");
      out.write("            <div class=\"col-sm-6 col-md-3\">\n");
      out.write("                <div class=\"info-card\">\n");
      out.write("                    <i class=\"fas fa-star\"></i>\n");
      out.write("                    <h5>Fireflies</h5>\n");
      out.write("                    <p>One of the world's best firefly habitats along the Selangor River</p>\n");
      out.write("                </div>\n");
      out.write("            </div>\n");
      out.write("            <div class=\"col-sm-6 col-md-3\">\n");
      out.write("                <div class=\"info-card\">\n");
      out.write("                    <i class=\"fas fa-landmark\"></i>\n");
      out.write("                    <h5>Bukit Melawati</h5>\n");
      out.write("                    <p>Historical hilltop fort with silver leaf monkeys and colonial heritage</p>\n");
      out.write("                </div>\n");
      out.write("            </div>\n");
      out.write("            <div class=\"col-sm-6 col-md-3\">\n");
      out.write("                <div class=\"info-card\">\n");
      out.write("                    <i class=\"fas fa-fish\"></i>\n");
      out.write("                    <h5>Seafood</h5>\n");
      out.write("                    <p>Fresh local seafood restaurants serving iconic chilli crab and more</p>\n");
      out.write("                </div>\n");
      out.write("            </div>\n");
      out.write("        </div>\n");
      out.write("    </div>\n");
      out.write("</section>\n");
      out.write("\n");
      out.write("<!-- ===== ABOUT ===== -->\n");
      out.write("<section class=\"section-padding\">\n");
      out.write("    <div class=\"container\">\n");
      out.write("        <div class=\"row align-items-center g-5\">\n");
      out.write("            <div class=\"col-lg-6\">\n");
      out.write("                <div class=\"hero-badge text-start\">About the Destination</div>\n");
      out.write("                <h2 class=\"section-title mt-2\">A Hidden Gem on Selangor's Coast</h2>\n");
      out.write("                <hr class=\"title-divider ms-0\">\n");
      out.write("                <p class=\"text-muted mb-3\" style=\"line-height:1.8;\">\n");
      out.write("                    Kuala Selangor is a peaceful coastal town located about 70 km north of Kuala Lumpur.\n");
      out.write("                    Once the seat of the Selangor Sultanate, it blends rich historical heritage with\n");
      out.write("                    stunning natural wonders that draw visitors from around the world.\n");
      out.write("                </p>\n");
      out.write("                <p class=\"text-muted mb-4\" style=\"line-height:1.8;\">\n");
      out.write("                    The town is best known for the <strong>Sky Mirror</strong> — a sandbar at Kuala\n");
      out.write("                    Selangor's Sasaran beach that emerges during low tide, creating a mirror-like\n");
      out.write("                    surface that reflects the sky in awe-inspiring ways. Come nightfall, witness\n");
      out.write("                    thousands of synchronised fireflies illuminate the mangroves along the Selangor River.\n");
      out.write("                </p>\n");
      out.write("                <a href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/activities.jsp\" class=\"btn-primary-custom btn\">\n");
      out.write("                    <i class=\"fas fa-compass me-2\"></i>See What To Do\n");
      out.write("                </a>\n");
      out.write("            </div>\n");
      out.write("            <div class=\"col-lg-6\">\n");
      out.write("                <img src=\"https://picsum.photos/seed/kuala-selangor-town/700/480\"\n");
      out.write("                     alt=\"Kuala Selangor Waterfront\"\n");
      out.write("                     class=\"img-fluid rounded-3 shadow-lg\" style=\"object-fit:cover; max-height:400px; width:100%;\">\n");
      out.write("            </div>\n");
      out.write("        </div>\n");
      out.write("    </div>\n");
      out.write("</section>\n");
      out.write("\n");
      out.write("<!-- ===== SKY MIRROR HIGHLIGHT ===== -->\n");
      out.write("<section class=\"section-padding bg-light-custom\">\n");
      out.write("    <div class=\"container\">\n");
      out.write("        <div class=\"row align-items-center g-5\">\n");
      out.write("            <div class=\"col-lg-6 order-lg-2\">\n");
      out.write("                <div class=\"hero-badge\">Featured Attraction</div>\n");
      out.write("                <h2 class=\"section-title mt-2\">The Sky Mirror Experience</h2>\n");
      out.write("                <hr class=\"title-divider ms-0\">\n");
      out.write("                <p class=\"text-muted mb-3\" style=\"line-height:1.8;\">\n");
      out.write("                    Sasaran's Sky Mirror is one of Malaysia's most photogenic natural wonders.\n");
      out.write("                    Accessible only by boat, this vast sandbar appears twice a month during low tide,\n");
      out.write("                    producing a perfect mirror reflection of the sky and clouds.\n");
      out.write("                </p>\n");
      out.write("                <ul class=\"list-unstyled mb-4\">\n");
      out.write("                    <li class=\"mb-2\"><i class=\"fas fa-check-circle text-success me-2\"></i>Best visited during early morning for golden reflections</li>\n");
      out.write("                    <li class=\"mb-2\"><i class=\"fas fa-check-circle text-success me-2\"></i>Accessible via a 15-minute boat ride from Pasir Penambang</li>\n");
      out.write("                    <li class=\"mb-2\"><i class=\"fas fa-check-circle text-success me-2\"></i>Appears only during specific low-tide windows each month</li>\n");
      out.write("                    <li class=\"mb-2\"><i class=\"fas fa-check-circle text-success me-2\"></i>Perfect for photography and unforgettable memories</li>\n");
      out.write("                </ul>\n");
      out.write("                <a href=\"https://maps.app.goo.gl/YybGbQhGVnVqTVDp6\" target=\"_blank\" class=\"maps-link-btn\">\n");
      out.write("                    <i class=\"fab fa-google\"></i> Open in Google Maps\n");
      out.write("                </a>\n");
      out.write("            </div>\n");
      out.write("            <div class=\"col-lg-6 order-lg-1\">\n");
      out.write("                <img src=\"https://picsum.photos/seed/sky-mirror-sasaran/700/480\"\n");
      out.write("                     alt=\"Sky Mirror at Kuala Selangor\"\n");
      out.write("                     class=\"img-fluid rounded-3 shadow-lg\" style=\"object-fit:cover; max-height:400px; width:100%;\">\n");
      out.write("            </div>\n");
      out.write("        </div>\n");
      out.write("    </div>\n");
      out.write("</section>\n");
      out.write("\n");
      out.write("<!-- ===== QUICK LINKS ===== -->\n");
      out.write("<section class=\"section-padding\">\n");
      out.write("    <div class=\"container text-center\">\n");
      out.write("        <h2 class=\"section-title\">Plan Your Visit</h2>\n");
      out.write("        <p class=\"section-subtitle\">Everything you need to make your Kuala Selangor trip unforgettable</p>\n");
      out.write("        <div class=\"row g-4 justify-content-center\">\n");
      out.write("            <div class=\"col-sm-6 col-md-3\">\n");
      out.write("                <a href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/gallery.jsp\" class=\"text-decoration-none\">\n");
      out.write("                    <div class=\"feature-card p-4 h-100 text-center\">\n");
      out.write("                        <i class=\"fas fa-images fa-2x text-primary-custom mb-3\"></i>\n");
      out.write("                        <h5 class=\"fw-bold\">Gallery</h5>\n");
      out.write("                        <p class=\"text-muted small\">8 stunning photos of the destination</p>\n");
      out.write("                    </div>\n");
      out.write("                </a>\n");
      out.write("            </div>\n");
      out.write("            <div class=\"col-sm-6 col-md-3\">\n");
      out.write("                <a href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/activities.jsp\" class=\"text-decoration-none\">\n");
      out.write("                    <div class=\"feature-card p-4 h-100 text-center\">\n");
      out.write("                        <i class=\"fas fa-hiking fa-2x text-primary-custom mb-3\"></i>\n");
      out.write("                        <h5 class=\"fw-bold\">Activities</h5>\n");
      out.write("                        <p class=\"text-muted small\">4 top things to do in Kuala Selangor</p>\n");
      out.write("                    </div>\n");
      out.write("                </a>\n");
      out.write("            </div>\n");
      out.write("            <div class=\"col-sm-6 col-md-3\">\n");
      out.write("                <a href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/accommodation.jsp\" class=\"text-decoration-none\">\n");
      out.write("                    <div class=\"feature-card p-4 h-100 text-center\">\n");
      out.write("                        <i class=\"fas fa-bed fa-2x text-primary-custom mb-3\"></i>\n");
      out.write("                        <h5 class=\"fw-bold\">Accommodation</h5>\n");
      out.write("                        <p class=\"text-muted small\">4 places to stay for every budget</p>\n");
      out.write("                    </div>\n");
      out.write("                </a>\n");
      out.write("            </div>\n");
      out.write("            <div class=\"col-sm-6 col-md-3\">\n");
      out.write("                <a href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/contact.jsp\" class=\"text-decoration-none\">\n");
      out.write("                    <div class=\"feature-card p-4 h-100 text-center\">\n");
      out.write("                        <i class=\"fas fa-envelope fa-2x text-primary-custom mb-3\"></i>\n");
      out.write("                        <h5 class=\"fw-bold\">Inquiry</h5>\n");
      out.write("                        <p class=\"text-muted small\">Get in touch — we're happy to help</p>\n");
      out.write("                    </div>\n");
      out.write("                </a>\n");
      out.write("            </div>\n");
      out.write("        </div>\n");
      out.write("    </div>\n");
      out.write("</section>\n");
      out.write("\n");
      out.write("<footer>\n");
      out.write("    <div class=\"footer-stripe\"></div>\n");
      out.write("    <div class=\"footer-body\">\n");
      out.write("        <div class=\"container d-flex flex-column flex-md-row align-items-center justify-content-between gap-2\">\n");
      out.write("            <img src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/images/vm2026/logo.png\"\n");
      out.write("                 alt=\"Visit Malaysia 2026\" style=\"height:36px; opacity:0.85;\">\n");
      out.write("            <p class=\"mb-0\">&copy; 2026 Kuala Selangor Tourism &mdash; CSC584 Individual Assignment</p>\n");
      out.write("            <a href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/developer.jsp\">Developer Info</a>\n");
      out.write("        </div>\n");
      out.write("    </div>\n");
      out.write("</footer>\n");
      out.write("\n");
      out.write("<script src=\"https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/js/bootstrap.bundle.min.js\"></script>\n");
      out.write("</body>\n");
      out.write("</html>\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof jakarta.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
