/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: jetty/12.0.21
 * Generated at: 2026-06-30 06:27:16 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.admin;

import jakarta.servlet.*;
import jakarta.servlet.http.*;
import jakarta.servlet.jsp.*;
import java.sql.*;
import com.uitm.csc584.tourism.model.Db;

public final class dashboard_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports,
                 org.apache.jasper.runtime.JspSourceDirectives {

  private static final jakarta.servlet.jsp.JspFactory _jspxFactory =
          jakarta.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.LinkedHashSet<>(6);
    _jspx_imports_packages.add("java.sql");
    _jspx_imports_packages.add("jakarta.servlet");
    _jspx_imports_packages.add("jakarta.servlet.http");
    _jspx_imports_packages.add("jakarta.servlet.jsp");
    _jspx_imports_classes = new java.util.LinkedHashSet<>(2);
    _jspx_imports_classes.add("com.uitm.csc584.tourism.model.Db");
  }

  private volatile jakarta.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public boolean getErrorOnELNotFound() {
    return false;
  }

  public jakarta.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final jakarta.servlet.http.HttpServletRequest request, final jakarta.servlet.http.HttpServletResponse response)
      throws java.io.IOException, jakarta.servlet.ServletException {

    if (!jakarta.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final jakarta.servlet.jsp.PageContext pageContext;
    jakarta.servlet.http.HttpSession session = null;
    final jakarta.servlet.ServletContext application;
    final jakarta.servlet.ServletConfig config;
    jakarta.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    jakarta.servlet.jsp.JspWriter _jspx_out = null;
    jakarta.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write('\n');

    // Defence-in-depth check (filter already handles this, but belt-and-suspenders)
    if (session.getAttribute("adminUser") == null) {
        response.sendRedirect(request.getContextPath() + "/admin/login.jsp");
        return;
    }
    String adminUser = (String) session.getAttribute("adminUser");

      out.write("\n");
      out.write("<!DOCTYPE html>\n");
      out.write("<html lang=\"en\">\n");
      out.write("<head>\n");
      out.write("    <meta charset=\"UTF-8\">\n");
      out.write("    <meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">\n");
      out.write("    <title>Admin Dashboard — Kuala Selangor Tourism</title>\n");
      out.write("    <link rel=\"stylesheet\" href=\"https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css\">\n");
      out.write("    <link rel=\"stylesheet\" href=\"https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.5.0/css/all.min.css\">\n");
      out.write("    <!-- DataTables CSS -->\n");
      out.write("    <link rel=\"stylesheet\" href=\"https://cdn.datatables.net/1.13.8/css/dataTables.bootstrap5.min.css\">\n");
      out.write("    <link rel=\"stylesheet\" href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/css/style.css\">\n");
      out.write("    <style>\n");
      out.write("        body { background-color: #f4f6f9; }\n");
      out.write("        .top-nav {\n");
      out.write("            background-color: #1c2833;\n");
      out.write("            padding: 0.75rem 1.5rem;\n");
      out.write("            display: flex;\n");
      out.write("            align-items: center;\n");
      out.write("            justify-content: space-between;\n");
      out.write("        }\n");
      out.write("        .top-nav .brand { color: white; font-size: 1.15rem; font-weight: 700; }\n");
      out.write("        .top-nav .brand span { color: #e8a020; }\n");
      out.write("        .top-nav .admin-info { color: rgba(255,255,255,0.8); font-size: 0.9rem; }\n");
      out.write("        .sidebar {\n");
      out.write("            background-color: #1c2833;\n");
      out.write("            min-height: calc(100vh - 54px);\n");
      out.write("            padding-top: 1.5rem;\n");
      out.write("        }\n");
      out.write("        .sidebar a {\n");
      out.write("            display: flex;\n");
      out.write("            align-items: center;\n");
      out.write("            gap: 0.75rem;\n");
      out.write("            color: rgba(255,255,255,0.75);\n");
      out.write("            padding: 0.7rem 1.5rem;\n");
      out.write("            text-decoration: none;\n");
      out.write("            font-weight: 500;\n");
      out.write("            border-left: 3px solid transparent;\n");
      out.write("            transition: all 0.2s;\n");
      out.write("        }\n");
      out.write("        .sidebar a:hover, .sidebar a.active {\n");
      out.write("            color: white;\n");
      out.write("            background-color: rgba(255,255,255,0.08);\n");
      out.write("            border-left-color: #e8a020;\n");
      out.write("        }\n");
      out.write("        .sidebar a i { width: 18px; }\n");
      out.write("        .content-area { padding: 2rem; }\n");
      out.write("    </style>\n");
      out.write("</head>\n");
      out.write("<body>\n");
      out.write("\n");
      out.write("<!-- Top Navigation -->\n");
      out.write("<div class=\"top-nav\">\n");
      out.write("    <div class=\"brand\"><i class=\"fas fa-umbrella-beach me-2\"></i>Kuala <span>Selangor</span> Admin</div>\n");
      out.write("    <div class=\"d-flex align-items-center gap-3\">\n");
      out.write("        <span class=\"admin-info\"><i class=\"fas fa-user-circle me-1\"></i>Logged in as <strong>");
      out.print( adminUser );
      out.write("</strong></span>\n");
      out.write("        <a href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/admin/logout\"\n");
      out.write("           class=\"btn btn-sm btn-outline-light\">\n");
      out.write("            <i class=\"fas fa-right-from-bracket me-1\"></i>Logout\n");
      out.write("        </a>\n");
      out.write("    </div>\n");
      out.write("</div>\n");
      out.write("\n");
      out.write("<div class=\"d-flex\">\n");
      out.write("    <!-- Sidebar -->\n");
      out.write("    <div class=\"sidebar\" style=\"width: 240px; flex-shrink:0;\">\n");
      out.write("        <a href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/admin/dashboard.jsp\" class=\"active\">\n");
      out.write("            <i class=\"fas fa-table-list\"></i> Inquiries\n");
      out.write("        </a>\n");
      out.write("        <a href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/index.jsp\" target=\"_blank\">\n");
      out.write("            <i class=\"fas fa-globe\"></i> View Public Site\n");
      out.write("        </a>\n");
      out.write("        <a href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/admin/logout\">\n");
      out.write("            <i class=\"fas fa-right-from-bracket\"></i> Logout\n");
      out.write("        </a>\n");
      out.write("    </div>\n");
      out.write("\n");
      out.write("    <!-- Main Content -->\n");
      out.write("    <div class=\"content-area flex-grow-1\">\n");
      out.write("\n");
      out.write("        <!-- Page Title + Stat -->\n");
      out.write("        <div class=\"d-flex align-items-center justify-content-between mb-4 flex-wrap gap-3\">\n");
      out.write("            <div>\n");
      out.write("                <h3 class=\"fw-bold mb-1\" style=\"color:#1c2833;\">Visitor Inquiries</h3>\n");
      out.write("                <p class=\"text-muted mb-0\">All inquiries submitted via the public contact form</p>\n");
      out.write("            </div>\n");
      out.write("        </div>\n");
      out.write("\n");
      out.write("        <!-- Inquiries Table Card -->\n");
      out.write("        <div class=\"admin-card\">\n");
      out.write("            ");

                int totalCount = 0;
                Connection conn = null;
                PreparedStatement ps = null;
                ResultSet rs = null;
                String dbError = null;

                try {
                    conn = Db.getConnection();

                    // Get total count for stat card
                    PreparedStatement countPs = conn.prepareStatement("SELECT COUNT(*) FROM inquiries");
                    ResultSet countRs = countPs.executeQuery();
                    if (countRs.next()) totalCount = countRs.getInt(1);
                    countRs.close();
                    countPs.close();
            
      out.write("\n");
      out.write("\n");
      out.write("            <!-- Stat Card -->\n");
      out.write("            <div class=\"stat-card blue mb-4\" style=\"max-width:280px;\">\n");
      out.write("                <i class=\"fas fa-envelope-open-text\"></i>\n");
      out.write("                <div>\n");
      out.write("                    <div class=\"stat-number\">");
      out.print( totalCount );
      out.write("</div>\n");
      out.write("                    <div class=\"stat-label\">Total Inquiries Received</div>\n");
      out.write("                </div>\n");
      out.write("            </div>\n");
      out.write("\n");
      out.write("            <table id=\"inquiriesTable\" class=\"table table-striped table-hover w-100\">\n");
      out.write("                <thead class=\"table-dark\">\n");
      out.write("                    <tr>\n");
      out.write("                        <th>#</th>\n");
      out.write("                        <th>Name</th>\n");
      out.write("                        <th>Contact</th>\n");
      out.write("                        <th>Gender</th>\n");
      out.write("                        <th>Email</th>\n");
      out.write("                        <th>How Heard</th>\n");
      out.write("                        <th>Message</th>\n");
      out.write("                        <th>Submitted At</th>\n");
      out.write("                    </tr>\n");
      out.write("                </thead>\n");
      out.write("                <tbody>\n");
      out.write("                    ");

                        ps = conn.prepareStatement(
                            "SELECT id, name, contact_number, gender, email, how_heard, message, submitted_at " +
                            "FROM inquiries ORDER BY submitted_at DESC");
                        rs = ps.executeQuery();
                        while (rs.next()) {
                            String msgText = rs.getString("message");
                            if (msgText != null && msgText.length() > 80) {
                                msgText = msgText.substring(0, 80) + "...";
                            }
                    
      out.write("\n");
      out.write("                    <tr>\n");
      out.write("                        <td>");
      out.print( rs.getInt("id") );
      out.write("</td>\n");
      out.write("                        <td>");
      out.print( rs.getString("name") );
      out.write("</td>\n");
      out.write("                        <td>");
      out.print( rs.getString("contact_number") );
      out.write("</td>\n");
      out.write("                        <td>");
      out.print( rs.getString("gender") );
      out.write("</td>\n");
      out.write("                        <td>");
      out.print( rs.getString("email") );
      out.write("</td>\n");
      out.write("                        <td>");
      out.print( rs.getString("how_heard") );
      out.write("</td>\n");
      out.write("                        <td style=\"max-width:200px; word-break:break-word;\">");
      out.print( msgText );
      out.write("</td>\n");
      out.write("                        <td>");
      out.print( rs.getTimestamp("submitted_at") );
      out.write("</td>\n");
      out.write("                    </tr>\n");
      out.write("                    ");

                        }
                    } catch (SQLException e) {
                        dbError = e.getMessage();
                    } finally {
                        if (rs   != null) try { rs.close();   } catch (SQLException ignored) {}
                        if (ps   != null) try { ps.close();   } catch (SQLException ignored) {}
                        if (conn != null) try { conn.close(); } catch (SQLException ignored) {}
                    }
                    if (dbError != null) {
                    
      out.write("\n");
      out.write("                        <tr><td colspan=\"8\" class=\"text-danger text-center\">\n");
      out.write("                            Database error: ");
      out.print( dbError );
      out.write("\n");
      out.write("                        </td></tr>\n");
      out.write("                    ");

                    }
                    
      out.write("\n");
      out.write("                </tbody>\n");
      out.write("            </table>\n");
      out.write("        </div><!-- /admin-card -->\n");
      out.write("    </div><!-- /content-area -->\n");
      out.write("</div><!-- /d-flex -->\n");
      out.write("\n");
      out.write("<!-- JS -->\n");
      out.write("<script src=\"https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/js/bootstrap.bundle.min.js\"></script>\n");
      out.write("<script src=\"https://code.jquery.com/jquery-3.7.1.min.js\"></script>\n");
      out.write("<script src=\"https://cdn.datatables.net/1.13.8/js/jquery.dataTables.min.js\"></script>\n");
      out.write("<script src=\"https://cdn.datatables.net/1.13.8/js/dataTables.bootstrap5.min.js\"></script>\n");
      out.write("<script>\n");
      out.write("    $(document).ready(function () {\n");
      out.write("        $('#inquiriesTable').DataTable({\n");
      out.write("            order: [[7, 'desc']],\n");
      out.write("            pageLength: 10,\n");
      out.write("            lengthMenu: [5, 10, 25, 50],\n");
      out.write("            language: {\n");
      out.write("                search: 'Search inquiries:',\n");
      out.write("                emptyTable: 'No inquiries have been submitted yet.'\n");
      out.write("            },\n");
      out.write("            columnDefs: [\n");
      out.write("                { orderable: false, targets: [6] }\n");
      out.write("            ]\n");
      out.write("        });\n");
      out.write("    });\n");
      out.write("</script>\n");
      out.write("</body>\n");
      out.write("</html>\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof jakarta.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
